<a href="https://colab.research.google.com/github/chengcheny/Testing/blob/master/Pytorch_learning_sripts_from_org0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[4.6784e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 5)
print(x)

tensor([[0.7960, 0.7604, 0.4896, 0.6109, 0.9151],
        [0.9137, 0.9093, 0.8970, 0.9979, 0.7056],
        [0.4532, 0.2321, 0.0654, 0.0290, 0.7598],
        [0.7765, 0.5576, 0.3853, 0.5745, 0.1015],
        [0.8720, 0.0909, 0.4802, 0.5832, 0.1138]])


In [6]:
x = torch.zeros(5 ,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5, 5, 3])
print(x)

tensor([5, 5, 3])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.6049,  1.1499, -0.1561],
        [-0.8737,  1.3926,  1.1809],
        [ 1.0817,  1.1583, -0.2107],
        [ 0.7588, -1.1396,  0.0434],
        [ 0.0686,  0.1317, -0.2106]])


In [17]:
print(x.size())

torch.Size([5, 3])


In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5574e+00,  1.2863e+00,  4.1639e-02],
        [-7.1847e-01,  1.4109e+00,  1.6322e+00],
        [ 1.3728e+00,  1.4410e+00,  4.2229e-02],
        [ 8.4102e-01, -9.0374e-01,  2.4062e-01],
        [ 6.7551e-01,  9.2889e-01, -6.6803e-04]])


In [20]:
print(x)
print(y)
print(torch.add(x,y))

tensor([[ 0.6049,  1.1499, -0.1561],
        [-0.8737,  1.3926,  1.1809],
        [ 1.0817,  1.1583, -0.2107],
        [ 0.7588, -1.1396,  0.0434],
        [ 0.0686,  0.1317, -0.2106]])
tensor([[0.9525, 0.1364, 0.1977],
        [0.1552, 0.0184, 0.4513],
        [0.2911, 0.2827, 0.2529],
        [0.0822, 0.2359, 0.1973],
        [0.6069, 0.7972, 0.2100]])
tensor([[ 1.5574e+00,  1.2863e+00,  4.1639e-02],
        [-7.1847e-01,  1.4109e+00,  1.6322e+00],
        [ 1.3728e+00,  1.4410e+00,  4.2229e-02],
        [ 8.4102e-01, -9.0374e-01,  2.4062e-01],
        [ 6.7551e-01,  9.2889e-01, -6.6803e-04]])


In [24]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5574e+00,  1.2863e+00,  4.1639e-02],
        [-7.1847e-01,  1.4109e+00,  1.6322e+00],
        [ 1.3728e+00,  1.4410e+00,  4.2229e-02],
        [ 8.4102e-01, -9.0374e-01,  2.4062e-01],
        [ 6.7551e-01,  9.2889e-01, -6.6803e-04]])


In [25]:
y.add_(x)
print(y)

tensor([[ 1.5574e+00,  1.2863e+00,  4.1639e-02],
        [-7.1847e-01,  1.4109e+00,  1.6322e+00],
        [ 1.3728e+00,  1.4410e+00,  4.2229e-02],
        [ 8.4102e-01, -9.0374e-01,  2.4062e-01],
        [ 6.7551e-01,  9.2889e-01, -6.6803e-04]])


In [27]:
print(x[:, 1])
print(x)

tensor([ 1.1499,  1.3926,  1.1583, -1.1396,  0.1317])
tensor([[ 0.6049,  1.1499, -0.1561],
        [-0.8737,  1.3926,  1.1809],
        [ 1.0817,  1.1583, -0.2107],
        [ 0.7588, -1.1396,  0.0434],
        [ 0.0686,  0.1317, -0.2106]])


In [30]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3438])
0.343763142824173


In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [41]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
