<a href="https://colab.research.google.com/github/chengcheny/Testing/blob/master/Pytorch_learning_sripts_from_org_ipynb1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from torch.autograd import Variable

In [6]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor, requires_grad=True)
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [10]:
v_out.backward(
    print(variable.grad)
)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


RuntimeError: ignored

In [11]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
